<?php

namespace Database\Seeders;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class SnapshotSeeder extends Seeder
{
    /**
     * Imports a JSON snapshot generated by `php artisan db:export-snapshot`.
     *
     * - Portable across MySQL and PostgreSQL.
     * - Idempotent: hashes the manifest and skips the import when the same
     *   snapshot was already loaded (via the `snapshot_imports` control table).
     *   This makes it safe to call on every container boot in Render.
     * - Resets PostgreSQL sequences after insert so future auto-increments
     *   start at MAX(id)+1.
     * - FK ordering: parents first, dependents after, based on a curated list
     *   plus alphabetical fallback for any extra tables in the manifest.
     */
    public function run(): void
    {
        $exportsDir = database_path('exports');
        $manifestFile = $exportsDir . '/_manifest.json';

        if (!is_file($manifestFile)) {
            $this->command?->error("Manifest not found at {$manifestFile}. Run: php artisan db:export-snapshot");
            return;
        }

        $manifestRaw = file_get_contents($manifestFile);
        $manifest = json_decode($manifestRaw, true);
        if (!is_array($manifest) || empty($manifest['tables'])) {
            $this->command?->error('Manifest is empty or invalid.');
            return;
        }

        $manifestHash = hash('sha256', $manifestRaw);
        $force = (bool) (env('SNAPSHOT_FORCE_REIMPORT', false));

        $this->ensureControlTable();

        if (!$force && $this->hashAlreadyImported($manifestHash)) {
            $this->command?->info("[SnapshotSeeder] Snapshot {$manifestHash} already imported. Skipping. Set SNAPSHOT_FORCE_REIMPORT=true to override.");
            return;
        }

        // Tables to load in this dependency-aware order. Anything not listed here
        // will be loaded at the end (alphabetically) — safe for tables without FKs.
        $loadOrder = [
            // Independent / lookup tables
            'vendor_types',
            'tag_types',
            'ranking_categories',
            'badges',
            'events',

            // Auth/identity
            'users',
            'vendors',
            'admins',

            // Vendor-related
            'profiles',
            'tags',
            'vendor_rankings',
            'reviews',
            'endorsements',
            'favorites',
            'pairings',
            'vendor_connections',

            // Couples / planning
            'inquiries',
            'meetings',
            'referrals',
            'couple_timeline_drafts',
            'vendor_timeline_drafts',

            // Subscriptions
            'subscriptions',
            'subscription_items',

            // Chat
            'chat_conversations',
            'chat_participation',
            'chat_messages',
            'chat_message_notifications',
            'chat_message_attachments',
        ];

        $availableTables = collect($manifest['tables'])->pluck('name')->all();

        // Final order = preferred order (keep only existing) + remaining tables
        $orderedTables = array_values(array_intersect($loadOrder, $availableTables));
        $remaining = array_diff($availableTables, $orderedTables);
        sort($remaining);
        $orderedTables = array_merge($orderedTables, $remaining);

        $driver = DB::getDriverName();

        // Disable FK checks during the load
        $this->disableForeignKeyChecks($driver);

        $insertedTotal = 0;

        foreach ($orderedTables as $table) {
            $file = $exportsDir . '/' . $table . '.json';
            if (!is_file($file)) {
                continue;
            }
            if (!Schema::hasTable($table)) {
                $this->command?->warn("  - {$table}: table does not exist in target DB, skipping");
                continue;
            }

            $rows = json_decode(file_get_contents($file), true);
            if (!is_array($rows) || count($rows) === 0) {
                continue;
            }

            $rows = $this->normalizeRowsForDriver($rows, $driver, $table);
            $rows = $this->filterRowsForTable($rows, $table);

            try {
                DB::table($table)->truncate();
            } catch (\Throwable $e) {
                // Some drivers (PostgreSQL with FK) require CASCADE — fall back to delete()
                DB::table($table)->delete();
            }

            // Insert in chunks for performance and to avoid MySQL packet size errors
            $chunks = array_chunk($rows, 200);
            foreach ($chunks as $chunk) {
                DB::table($table)->insert($chunk);
            }

            $count = count($rows);
            $insertedTotal += $count;

            // Reset auto-increment sequence on PostgreSQL so id columns work
            if ($driver === 'pgsql' && Schema::hasColumn($table, 'id')) {
                $this->resetPgSequence($table, 'id');
            }

            $this->command?->info(sprintf("  + %-40s %6d rows", $table, $count));
        }

        $this->enableForeignKeyChecks($driver);

        $this->recordImport($manifestHash, $insertedTotal, count($orderedTables));

        $this->command?->info("[SnapshotSeeder] Import complete. Total rows inserted: {$insertedTotal}. Hash: {$manifestHash}");
    }

    private function ensureControlTable(): void
    {
        if (Schema::hasTable('snapshot_imports')) {
            return;
        }

        Schema::create('snapshot_imports', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('manifest_hash', 64)->unique();
            $table->unsignedBigInteger('rows_imported')->default(0);
            $table->unsignedInteger('tables_imported')->default(0);
            $table->timestamp('imported_at')->useCurrent();
        });
    }

    private function hashAlreadyImported(string $hash): bool
    {
        try {
            return DB::table('snapshot_imports')->where('manifest_hash', $hash)->exists();
        } catch (\Throwable $e) {
            return false;
        }
    }

    private function recordImport(string $hash, int $rows, int $tables): void
    {
        try {
            DB::table('snapshot_imports')->updateOrInsert(
                ['manifest_hash' => $hash],
                [
                    'rows_imported' => $rows,
                    'tables_imported' => $tables,
                    'imported_at' => now(),
                ]
            );
        } catch (\Throwable $e) {
            $this->command?->warn("[SnapshotSeeder] Could not record import marker: " . $e->getMessage());
        }
    }

    private function disableForeignKeyChecks(string $driver): void
    {
        try {
            if ($driver === 'mysql') {
                DB::statement('SET FOREIGN_KEY_CHECKS=0');
            } elseif ($driver === 'pgsql') {
                DB::statement('SET session_replication_role = replica');
            } elseif ($driver === 'sqlite') {
                DB::statement('PRAGMA foreign_keys = OFF');
            }
        } catch (\Throwable $e) {
            // Non-fatal: continue
        }
    }

    private function enableForeignKeyChecks(string $driver): void
    {
        try {
            if ($driver === 'mysql') {
                DB::statement('SET FOREIGN_KEY_CHECKS=1');
            } elseif ($driver === 'pgsql') {
                DB::statement('SET session_replication_role = DEFAULT');
            } elseif ($driver === 'sqlite') {
                DB::statement('PRAGMA foreign_keys = ON');
            }
        } catch (\Throwable $e) {
            // Non-fatal
        }
    }

    /**
     * Normalize rows to be driver-friendly:
     *  - PostgreSQL booleans: convert int 0/1 -> bool false/true for tinyint columns serialized from MySQL.
     *  - JSON strings: leave as-is (Postgres jsonb accepts strings via insert).
     *  - Empty strings on numeric columns are not changed here; rely on schema being permissive.
     */
    private function normalizeRowsForDriver(array $rows, string $driver, string $table): array
    {
        if ($driver !== 'pgsql') {
            return $rows;
        }

        $boolColumns = $this->getPgBooleanColumns($table);

        foreach ($rows as &$row) {
            foreach ($boolColumns as $col) {
                if (! array_key_exists($col, $row) || $row[$col] === null) {
                    continue;
                }

                if (is_bool($row[$col])) {
                    continue;
                }

                // MySQL tinyint(1): 1 = true; 0, -1, 2, … = false
                if (is_numeric($row[$col])) {
                    $row[$col] = ((int) $row[$col]) === 1;
                    continue;
                }

                if (is_string($row[$col]) && is_numeric(trim($row[$col]))) {
                    $row[$col] = ((int) trim($row[$col])) === 1;
                }
            }
        }
        unset($row);

        return $rows;
    }

    /**
     * @return list<string>
     */
    private function getPgBooleanColumns(string $table): array
    {
        static $cache = [];

        if (isset($cache[$table])) {
            return $cache[$table];
        }

        try {
            $columns = DB::select(
                'SELECT column_name FROM information_schema.columns
                 WHERE table_schema = current_schema()
                   AND table_name = ?
                   AND data_type = ?',
                [$table, 'boolean']
            );

            return $cache[$table] = array_column($columns, 'column_name');
        } catch (\Throwable $e) {
            return $cache[$table] = [];
        }
    }

    /**
     * Keep only columns that exist in the target schema (migrations may lag behind snapshot export).
     */
    private function filterRowsForTable(array $rows, string $table): array
    {
        $columns = Schema::getColumnListing($table);
        if ($columns === []) {
            return $rows;
        }

        $allowed = array_flip($columns);

        return array_map(static fn (array $row) => array_intersect_key($row, $allowed), $rows);
    }

    private function resetPgSequence(string $table, string $idCol = 'id'): void
    {
        try {
            $seq = DB::selectOne("SELECT pg_get_serial_sequence(?, ?) AS seq", [$table, $idCol]);
            if ($seq && !empty($seq->seq)) {
                DB::statement("SELECT setval(?, COALESCE((SELECT MAX({$idCol}) FROM \"{$table}\"), 1), true)", [$seq->seq]);
            }
        } catch (\Throwable $e) {
            // Non-fatal: sequence may not exist for this table
        }
    }
}
